<?php
/**
 * Enumerates and manages .avix files sitting in the local archives
 * directory — the "Backups" list, and the source of the Dashboard's "last
 * backup" stat. Cloud-stored archives (Milestone 6) are tracked separately
 * per destination and merged in by the Backups screen once that lands; this
 * class only ever looks at local disk.
 *
 * @package Avix_Migration
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Avix_Migration_Archive_Store {

	/**
	 * @return array[] Each: filename, path, bytes, created_at, type,
	 *                  site_url — newest first. Manifest reads are cheap
	 *                  (one header + a few KB of JSON) so doing one per
	 *                  archive is fine at the scale a single site
	 *                  accumulates backups.
	 */
	public static function list_all() {
		$dir = Avix_Migration_Util_Filesystem::archives_dir();
		if ( ! is_dir( $dir ) ) {
			return array();
		}

		$files = glob( $dir . '/*.avix' );
		if ( ! $files ) {
			return array();
		}

		$items = array();
		foreach ( $files as $file ) {
			$items[] = self::describe( $file );
		}

		usort(
			$items,
			function ( $a, $b ) {
				return $b['created_at'] <=> $a['created_at'];
			}
		);

		return $items;
	}

	public static function latest() {
		$all = self::list_all();
		return $all ? $all[0] : null;
	}

	/**
	 * @param string $filename Basename only — never accept a caller-supplied
	 *                         path here, only ever a name obtained from
	 *                         list_all() or generated by our own writer.
	 */
	public static function path_for( $filename ) {
		$filename = basename( (string) $filename );
		$dir      = Avix_Migration_Util_Filesystem::archives_dir();
		$path     = $dir . '/' . $filename;

		if ( ! Avix_Migration_Util_Filesystem::is_path_within( $dir, $path ) ) {
			return null;
		}
		return $path;
	}

	public static function delete( $filename ) {
		$path = self::path_for( $filename );
		if ( null === $path || ! file_exists( $path ) ) {
			return false;
		}
		@unlink( $path );
		@unlink( $path . '.checksum.json' );
		Avix_Migration_Util_Logger::info( 'plugin', 'Deleted archive.', array( 'file' => basename( $path ) ) );
		return true;
	}

	private static function describe( $file ) {
		$manifest = Avix_Migration_Archive_Reader::read_manifest_only( $file );
		$checksum_file = $file . '.checksum.json';
		$checksum = null;
		if ( is_readable( $checksum_file ) ) {
			$decoded = json_decode( (string) file_get_contents( $checksum_file ), true );
			$checksum = is_array( $decoded ) ? $decoded : null;
		}

		return array(
			'filename'   => basename( $file ),
			'path'       => $file,
			'bytes'      => (int) @filesize( $file ),
			'created_at' => $manifest['created_at'] ?? filemtime( $file ),
			'type'       => $manifest['archive_type'] ?? 'unknown',
			'site_url'   => $manifest['site']['site_url'] ?? '',
			'verified'   => null !== $checksum,
		);
	}
}
